#! /bin/bash

source /etc/bashup-settings

mkdir -p /mnt/backup

# Clean up crew
find /mnt/backup -type f -mtime +7 -exec rm {} \;

# Backup up dbs.
bashup-dbs

for dir in $BACKUP_DIRS; do
    bashup-dir $dir
done
